### ISSUE TITLE
feat: useCreditContext 구현 및 적용

### ISSUE THREAD

**Issue by KorpoQ** [sprint8team6/team-project1#40]
### @todo
- [x] useCreditContext 구현 및 적용 (@youmdang)
- [x] ListPage: useCreditContext 적용 (@youmdang)
- [x] Modal: useCreditContext 적용 (@KorpoQ)
