### ISSUE TITLE
feat: 모달 버그 수정 및 기타 세부 기능 구현

### ISSUE THREAD

**Issue by KorpoQ** [sprint8team6/team-project1#60]
### @todo
- [x] 도네이션 모달 오류 수정
- [x] 탭에 따른 올바른 투표 데이터 불러오기 수정
- [x] 추가 기능: 크레딧 후원 100 단위로 제한
- [x] 추가 기능: 스크롤 끝까지 내리면 자동 로딩
- [x] bugfix: 브라우저 확대/축소 상태에서 무한 스크롤이 구현되지 않은 부분 수정
