### ISSUE TITLE
feat: 기능 추가 및 잡다한 콘솔 에러 수정

### ISSUE THREAD

**Issue by KorpoQ** [sprint8team6/team-project1#64]
### @todo
- [x] feat: 홈페이지 타이틀 추가
- [x] feat: 홈페이지 favicon 및 아이콘 추가
- [x] feat: VoteModal 서버 에러 처리 추가
- [x] bugfix: 콘솔 에러 수정
- [x] style: 스타일 소폭 수정
